name: automated_testing_framework_plugin_firebase_storage
description: Library to use Google's Firebase Storage as a mechanism for automated tests and test results.
homepage: https://github.com/peiffer-innovations/automated_testing_framework_plugin_firebase_storage

version: 5.0.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  automated_testing_framework: ^4.0.0
  convert: ^3.0.1
  firebase_auth: ^3.3.18
  firebase_core: ^1.17.0
  firebase_storage: ^10.2.16
  flutter:
    sdk: flutter
  form_validation: ^2.1.0+2
  json_class: ^2.1.2+4
  logging: ^1.0.1
  static_translations: ^2.1.1

# dependency_overrides:
#   automated_testing_framework:
#     path: ../automated_testing_framework
#   automated_testing_framework_models:
#     path: ../automated_testing_framework_models

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
