name: 'automated_testing_framework_plugin_firebase_storage'
description: "Library to use Google's Firebase Storage as a mechanism for automated tests and test results."
homepage: 'https://github.com/peiffer-innovations/automated_testing_framework_plugin_firebase_storage'
version: '5.0.0+9'

environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  automated_testing_framework: '^4.0.2+1'
  convert: '^3.0.2'
  firebase_auth: '^3.5.1'
  firebase_core: '^1.20.0'
  firebase_storage: '^10.3.3'
  flutter: 
    sdk: 'flutter'
  form_validation: '^2.1.0+11'
  json_class: '^2.1.2+8'
  logging: '^1.0.2'
  static_translations: '^2.1.1+8'

dev_dependencies: 
  flutter_test: 
    sdk: 'flutter'


flutter: 
  uses-material-design: true
