name: automated_testing_framework_plugin_firebase_storage
description: Library to use Google's Firebase Storage as a mechanism for automated tests and test results.
homepage: https://github.com/peiffer-innovations/automated_testing_framework_plugin_firebase_storage

version: 3.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  automated_testing_framework: ^3.0.6
  convert: ^3.0.0
  firebase_auth: ^1.1.3
  firebase_core: ^1.1.0
  firebase_storage: ^8.0.5
  flutter:
    sdk: flutter
  form_validation: ^2.0.0
  json_class: ^2.0.0
  logging: ^1.0.1
  static_translations: ^2.0.1

# dependency_overrides:
#   automated_testing_framework:
#     path: ../automated_testing_framework
#   automated_testing_framework_models:
#     path: ../automated_testing_framework_models

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
